version: '3'

networks:
  nestj_crud:

services:
  postgres:
    image: postgres:11.5
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: nest_root
      POSTGRES_PASSWORD: nest_root123
      POSTGRES_DB: nest_crud
    networks:
      - nest_crud

  mysql:
    image: mysql:5.7
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: mysql_nest_crud
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: user_123
      MYSQL_ROOT_PASSWORD: nestjs123

  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - nest_crud
